wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/src/train_model.py
    python_version: 3.9.16
    cli_version: 0.15.4
    framework: fastai
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686733397.550234
    t:
      1:
      - 1
      - 4
      - 5
      - 53
      - 55
      - 89
      2:
      - 1
      - 4
      - 5
      - 53
      - 55
      - 89
      3:
      - 23
      4: 3.9.16
      5: 0.15.4
      8:
      - 5
